### ISSUE TITLE
Using MySQLite in my addon causes DarkRP to go into "MySQL mode"

### ISSUE THREAD

**Issue by WilliamVenner** [FPtje/MySQLite#9]
![](http://i.venner.io/chrome_2016-08-02_00-37-08.png)

I created a file in lua/includes/modues/bwhitelist_mysqlite.lua and put MySQLite in there (obviously). I require it and connect to a database and suddenly all of DarkRP's tables start showing up in my database.

What causes this?

**Comment by Bo98** [comment]
How are you connecting to the database? Are you using a "MySQLite_config" global variable or the MySQLite.initialize(config) function?

**Comment by WilliamVenner** [comment]
MySQLite.initialize

**Comment by Bo98** [comment]
Since the MySQLite module/table is added as a global variable when it is included/required, it is possible that using MySQLite elsewhere would replace an existing instance of MySQLite. I guess that's a reason why Lua deprecated traditional way of creating modules.

MySQLite could possibly return a table instead now that `include` supports that. Though care would need to be taken with backwards compatibility at least in DarkRP's case (i.e. DarkRP would need to add it to the global environment itself to not break addons).

**Comment by Bo98** [comment]
Other than that, renaming the module name in mysqlite.lua would be the only way to do it but that's not the nicest of solutions.

**Comment by WilliamVenner** [comment]
Yup, that fixed it. Thanks Bo.
